/** BOTRULES-020 — AI crawler robots.txt. Pure functions, no DOM. */

export const STORAGE_KEY = "botrules-020";

export const HEADER = [
  "# robots.txt generated by BOTRULES-020",
  "# https://build-100.com/020/",
].join("\n");

const ACTIONS = new Set(["allow", "disallow", "ignore"]);

export function asBotList(bots) {
  if (!bots) return [];
  if (Array.isArray(bots)) return bots.filter((b) => b && b.ua);
  if (Array.isArray(bots.bots)) return bots.bots.filter((b) => b && b.ua);
  return [];
}

export function normalizeAction(v) {
  const s = String(v ?? "")
    .trim()
    .toLowerCase();
  return ACTIONS.has(s) ? s : null;
}

function asSelections(selections) {
  if (!selections) return null;
  if (selections instanceof Map) return selections;
  if (typeof selections === "object") return selections;
  return null;
}

export function lookupSelection(selections, ua) {
  const bag = asSelections(selections);
  if (!bag || ua == null) return undefined;
  const want = String(ua);
  const wantLower = want.toLowerCase();
  if (bag instanceof Map) {
    if (bag.has(want)) return bag.get(want);
    for (const [k, v] of bag) {
      if (String(k).toLowerCase() === wantLower) return v;
    }
    return undefined;
  }
  if (Object.prototype.hasOwnProperty.call(bag, want)) return bag[want];
  for (const k of Object.keys(bag)) {
    if (k.toLowerCase() === wantLower) return bag[k];
  }
  return undefined;
}

export function selectionOf(selections, ua) {
  const raw = lookupSelection(selections, ua);
  if (raw === undefined) return "ignore";
  return normalizeAction(raw) || "ignore";
}

export function botIndex(bots) {
  const map = new Map();
  for (const bot of asBotList(bots)) {
    map.set(String(bot.ua).toLowerCase(), bot);
  }
  return map;
}

function isWildcardUa(ua) {
  return String(ua ?? "").trim() === "*";
}

function isWholeSitePath(value) {
  return String(value ?? "").trim() === "/";
}

function stripInlineComment(s) {
  const str = String(s ?? "");
  const i = str.indexOf(" #");
  if (i >= 0) return str.slice(0, i).trimEnd();
  return str;
}

function parseDirective(rawLine) {
  const trimmed = stripInlineComment(String(rawLine ?? "").trim());
  if (!trimmed || trimmed.startsWith("#")) return null;
  const m = trimmed.match(/^([A-Za-z][A-Za-z0-9-]*)\s*:\s*(.*)$/);
  if (!m) return { kind: "other", raw: rawLine };
  return {
    kind: "directive",
    field: m[1].toLowerCase(),
    value: m[2].trim(),
    raw: rawLine,
  };
}

/**
 * Split robots.txt into groups (UA + rules) and standalone lines (Sitemap/Host/comments).
 * Blank lines close a group. A new User-agent after rules have started starts a new group.
 */
export function tokenizeRobots(text) {
  const src = String(text ?? "").replace(/^\uFEFF/, "");
  const lines = src.split(/\r?\n/);
  const groups = [];
  const standalones = [];
  let cur = null;

  function close() {
    if (cur) groups.push(cur);
    cur = null;
  }

  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    const trimmed = raw.trim();
    if (!trimmed) {
      close();
      continue;
    }
    if (trimmed.startsWith("#")) {
      if (cur) {
        cur.lineIdx.push(i);
        cur.end = i;
      } else {
        standalones.push({ start: i, end: i, lineIdx: [i], kind: "comment" });
      }
      continue;
    }
    const dir = parseDirective(raw);
    if (!dir || dir.kind === "other") {
      if (cur) {
        cur.other = true;
        cur.lineIdx.push(i);
        cur.end = i;
      } else {
        standalones.push({ start: i, end: i, lineIdx: [i], kind: "other" });
      }
      continue;
    }
    if (dir.field === "sitemap" || dir.field === "host") {
      close();
      standalones.push({
        start: i,
        end: i,
        lineIdx: [i],
        kind: dir.field,
        value: dir.value,
      });
      continue;
    }
    if (dir.field === "user-agent") {
      if (cur && cur.rules.length) close();
      if (!cur) {
        cur = {
          uas: [],
          rules: [],
          start: i,
          end: i,
          lineIdx: [],
          other: false,
        };
      }
      cur.uas.push(dir.value);
      cur.lineIdx.push(i);
      cur.end = i;
      continue;
    }
    if (!cur) {
      standalones.push({
        start: i,
        end: i,
        lineIdx: [i],
        kind: "stray",
        field: dir.field,
        value: dir.value,
      });
      continue;
    }
    cur.rules.push({ field: dir.field, value: dir.value, raw });
    cur.lineIdx.push(i);
    cur.end = i;
  }
  close();
  return { lines, groups, standalones };
}

function simpleWholeSiteAction(group) {
  if (!group || group.other) return null;
  if (!group.uas || group.uas.length !== 1) return null;
  const ua = String(group.uas[0] ?? "").trim();
  if (!ua || isWildcardUa(ua)) return null;
  if (!group.rules.length) return null;
  let action = null;
  for (const rule of group.rules) {
    if (rule.field !== "allow" && rule.field !== "disallow") return null;
    if (!isWholeSitePath(rule.value)) return null;
    const next = rule.field === "allow" ? "allow" : "disallow";
    if (action && action !== next) return null;
    action = next;
  }
  return action ? { ua, action } : null;
}

export function parseRobots(text) {
  const { lines, groups, standalones } = tokenizeRobots(text);
  const known = {};
  const consumed = new Set();

  for (const g of groups) {
    const simple = simpleWholeSiteAction(g);
    if (!simple) continue;
    known[simple.ua] = simple.action;
    for (const i of g.lineIdx) consumed.add(i);
  }

  const extraIdx = [];
  for (let i = 0; i < lines.length; i++) {
    if (!consumed.has(i)) extraIdx.push(i);
  }

  // Drop leading/trailing blank lines in extras; keep internal blanks.
  while (extraIdx.length && !String(lines[extraIdx[0]]).trim()) extraIdx.shift();
  while (extraIdx.length && !String(lines[extraIdx[extraIdx.length - 1]]).trim()) extraIdx.pop();

  // Re-join keeping original gaps between remaining lines.
  let extras = "";
  if (extraIdx.length) {
    const parts = [];
    for (let n = 0; n < extraIdx.length; n++) {
      const i = extraIdx[n];
      if (n > 0) {
        const gap = extraIdx[n] - extraIdx[n - 1];
        if (gap === 1) parts.push("\n");
        else parts.push("\n\n");
      }
      parts.push(lines[i]);
    }
    extras = parts.join("");
  }

  void standalones;
  return { known, extras };
}

function knownUaSet(bots) {
  const set = new Set();
  for (const bot of asBotList(bots)) set.add(String(bot.ua).toLowerCase());
  return set;
}

/**
 * Drop table UAs from extras. Multi-UA groups keep remaining unknown agents.
 * Wildcard agent and Sitemap/Host are never stripped for being "known".
 */
export function stripKnownAgents(text, bots) {
  const src = String(text ?? "");
  if (!src.trim()) return "";
  const known = knownUaSet(bots);
  const { lines, groups, standalones } = tokenizeRobots(src);
  const drop = new Set();
  const rewrite = []; // { group, keepUas }

  for (const g of groups) {
    const keepUas = [];
    const dropUas = [];
    g.uas.forEach((ua, idx) => {
      const key = String(ua ?? "").trim().toLowerCase();
      if (key && known.has(key)) dropUas.push(idx);
      else keepUas.push(ua);
    });
    if (!dropUas.length) continue;
    if (!keepUas.length) {
      for (const i of g.lineIdx) drop.add(i);
    } else {
      rewrite.push({ group: g, keepUas });
    }
  }

  const out = [];
  const rewrittenStarts = new Set(rewrite.map((r) => r.group.start));
  const rewriteByStart = new Map(rewrite.map((r) => [r.group.start, r]));

  let i = 0;
  while (i < lines.length) {
    if (drop.has(i)) {
      i++;
      continue;
    }
    if (rewrittenStarts.has(i)) {
      const r = rewriteByStart.get(i);
      const g = r.group;
      const rebuilt = [];
      for (const ua of r.keepUas) rebuilt.push("User-agent: " + ua);
      for (const linei of g.lineIdx) {
        const dir = parseDirective(lines[linei]);
        if (dir && dir.kind === "directive" && dir.field === "user-agent") continue;
        rebuilt.push(lines[linei]);
      }
      out.push(rebuilt.join("\n"));
      i = g.end + 1;
      continue;
    }
    out.push(lines[i]);
    i++;
  }

  void standalones;
  let extras = out.join("\n");
  extras = extras.replace(/\n{3,}/g, "\n\n").trim();
  return extras;
}

function reconstructSimple(ua, action) {
  const rule = action === "allow" ? "Allow: /" : "Disallow: /";
  return "User-agent: " + ua + "\n" + rule;
}

export function applyPreset(name, bots) {
  const key = String(name ?? "")
    .trim()
    .toLowerCase();
  const list = asBotList(bots);
  let mode = "reset";
  if (
    key === "block-all" ||
    key === "block" ||
    key === "deny" ||
    key === "deny-all" ||
    key === "disallow" ||
    key === "全拦" ||
    key === "全拦 ai"
  ) {
    mode = "disallow";
  } else if (key === "allow-all" || key === "allow" || key === "全放行" || key === "全放行 ai") {
    mode = "allow";
  }
  const selections = {};
  for (const bot of list) {
    if (mode === "reset") {
      selections[bot.ua] = normalizeAction(bot.default) || "ignore";
    } else {
      selections[bot.ua] = mode;
    }
  }
  return selections;
}

export function hydrateSelections(bots, saved) {
  const base = applyPreset("reset", bots);
  if (!saved) return base;
  for (const bot of asBotList(bots)) {
    if (lookupSelection(saved, bot.ua) === undefined) continue;
    const a = selectionOf(saved, bot.ua);
    if (a === "allow" || a === "disallow" || a === "ignore") base[bot.ua] = a;
  }
  return base;
}

export function mergeSelections(parsed, bots, current) {
  const selections = hydrateSelections(bots, current || applyPreset("reset", bots));
  const knownRaw = parsed && parsed.known;
  const knownEntries = [];
  if (knownRaw instanceof Map) {
    for (const [k, v] of knownRaw) knownEntries.push([k, v]);
  } else if (knownRaw && typeof knownRaw === "object") {
    for (const k of Object.keys(knownRaw)) knownEntries.push([k, knownRaw[k]]);
  }

  const index = botIndex(bots);
  const unmatched = [];
  for (const [ua, action] of knownEntries) {
    const a = normalizeAction(action);
    if (a !== "allow" && a !== "disallow") continue;
    const bot = index.get(String(ua).trim().toLowerCase());
    if (bot) selections[bot.ua] = a;
    else unmatched.push({ ua: String(ua).trim(), action: a });
  }

  let extras = stripKnownAgents((parsed && parsed.extras) || "", bots);
  if (unmatched.length) {
    const extraBlocks = unmatched.map((u) => reconstructSimple(u.ua, u.action));
    extras = (extraBlocks.join("\n\n") + (extras ? "\n\n" + extras : "")).trim();
  }
  return { selections, extras };
}

export function buildRobots(bots, selections, extrasText) {
  const list = asBotList(bots);
  const blocks = [];
  const seen = new Set();
  for (const bot of list) {
    const key = String(bot.ua).toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    const action = selectionOf(selections, bot.ua);
    if (action === "allow") blocks.push("User-agent: " + bot.ua + "\nAllow: /");
    else if (action === "disallow") blocks.push("User-agent: " + bot.ua + "\nDisallow: /");
  }
  const extras = stripKnownAgents(extrasText || "", bots);
  const parts = [HEADER];
  if (blocks.length) parts.push(blocks.join("\n\n"));
  if (extras) parts.push(extras);
  let out = parts.join("\n\n");
  if (!out.endsWith("\n")) out += "\n";
  return out;
}

export function countActions(bots, selections) {
  const tallies = { allow: 0, disallow: 0, ignore: 0 };
  for (const bot of asBotList(bots)) {
    const a = selectionOf(selections, bot.ua);
    tallies[a] = (tallies[a] || 0) + 1;
  }
  return tallies;
}

export function listedAgents(text) {
  const names = [];
  const re = /^\s*user-agent\s*:\s*(.*?)\s*$/gim;
  let m;
  const src = String(text ?? "");
  while ((m = re.exec(src))) names.push(m[1].trim());
  return names;
}

export function buildShareText(bots, selections, lang) {
  const en = lang === "en";
  const tallies = countActions(bots, selections);
  const blocked = [];
  const allowed = [];
  for (const bot of asBotList(bots)) {
    const a = selectionOf(selections, bot.ua);
    if (a === "disallow") blocked.push(bot.ua);
    else if (a === "allow") allowed.push(bot.ua);
  }
  const lines = en
    ? [
        "Generated an AI robots.txt with BOTRULES-020.",
        "Blocked " + tallies.disallow + " · allowed " + tallies.allow + " · ignored " + tallies.ignore + ".",
      ]
    : [
        "用 BOTRULES-020 生成了 AI robots.txt",
        "拦 " + tallies.disallow + " · 放行 " + tallies.allow + " · 忽略 " + tallies.ignore + "。",
      ];
  if (blocked.length) {
    lines.push((en ? "Disallow: " : "拦：") + blocked.join(", "));
  }
  if (allowed.length) {
    lines.push((en ? "Allow: " : "放行：") + allowed.join(", "));
  }
  lines.push("https://build-100.com/020/");
  return lines.join("\n");
}

export function loadDraft(storage) {
  if (!storage || typeof storage.getItem !== "function") return null;
  try {
    const raw = storage.getItem(STORAGE_KEY);
    if (raw == null || raw === "") return null;
    const parsed = JSON.parse(raw);
    if (!parsed || typeof parsed !== "object") return null;
    const selections =
      parsed.selections && typeof parsed.selections === "object" && !Array.isArray(parsed.selections)
        ? parsed.selections
        : {};
    return { selections, extras: String(parsed.extras ?? "") };
  } catch {
    return null;
  }
}

export function saveDraft(draft, storage) {
  if (!storage || typeof storage.setItem !== "function") return false;
  try {
    const selections =
      draft && draft.selections && typeof draft.selections === "object" && !Array.isArray(draft.selections)
        ? draft.selections
        : {};
    storage.setItem(
      STORAGE_KEY,
      JSON.stringify({
        selections,
        extras: String(draft && draft.extras != null ? draft.extras : ""),
      })
    );
    return true;
  } catch {
    return false;
  }
}
